return {
  -- defaults
  { import = "plugins.defaults.conform" },
  { import = "plugins.defaults.lspconfig" },
  { import = "plugins.defaults.telescope" },
  { import = "plugins.defaults.luasnip" },
  { import = "plugins.defaults.cmp" },
  { import = "plugins.defaults.base46" },
  { import = "plugins.defaults.nvim-tree" },
  { import = "plugins.defaults.nvim-treesitter" },
  { import = "plugins.defaults.nvim-colorizer" },
  { import = "plugins.defaults.nvim-web-devicons" },
  { import = "plugins.defaults.ui" },
  { import = "plugins.defaults.mason" },
  { import = "plugins.defaults.whichkey" },
  { import = "plugins.defaults.blankline" },

  -- packages
  { import = "plugins.package.telescope-frecency" },
  { import = "plugins.package.persistence" },
  { import = "plugins.package.harpoon" },
  { import = "plugins.package.lsp-signature" },
  { import = "plugins.package.dap-ui" },
  { import = "plugins.package.dap-virtual-text" },
  { import = "plugins.package.rainbow-delimiters" },
  { import = "plugins.package.todo-comments" },
  { import = "plugins.package.trouble" },
  { import = "plugins.package.treesitter-textobjects" },
  -- { import = "plugins.package.scrollbar" },
  { import = "plugins.package.spider" },
  { import = "plugins.package.glance" },
  { import = "plugins.package.tiny-inline-diagnostic" },
  { import = "plugins.package.diffview" },
  { import = "plugins.package.better-escape" },
  { import = "plugins.package.dressing" },
  { import = "plugins.package.indent-scope" },
  { import = "plugins.package.smear-cursor" },
  { import = "plugins.package.harpoonline" },
  { import = "plugins.package.mini-surround" },
  { import = "plugins.package.emmet-vim" },
  { import = "plugins.package.fidget" },
  { import = "plugins.package.neoscroll" },
  { import = "plugins.package.volt" },
  { import = "plugins.package.menu" },
  { import = "plugins.package.minty" },
  { import = "plugins.package.markview" },
}
